package com.rj.appliedCs;

import java.util.HashMap;
import java.util.Map;

public class CountryCode {
    HashMap<String, String> countries = new HashMap<>();

    public void setup() {
        countries.put("AFG", "Afghanistan");
        countries.put("ALA", "Åland Islands");
        countries.put("ALB", "Albania");
        countries.put("DZA", "Algeria");
        countries.put("ASM", "American Samoa");
        countries.put("AND", "Andorra");
        countries.put("AGO", "Angola");
        countries.put("AIA", "Anguilla");
        countries.put("ATA", "Antarctica");
        countries.put("ATG", "Antigua and Barbuda");
        countries.put("ARG", "Argentina");
        countries.put("ARM", "Armenia");
        countries.put("ABW", "Aruba");
        countries.put("AUS", "Australia");
        countries.put("AUT", "Austria");
        countries.put("AZE", "Azerbaijan");
        countries.put("BHS", "Bahamas");
        countries.put("BHR", "Bahrain");
        countries.put("BGD", "Bangladesh");
        countries.put("BRB", "Barbados");
        countries.put("BLR", "Belarus");
        countries.put("BEL", "Belgium");
        countries.put("BLZ", "Belize");
        countries.put("BEN", "Benin");
        countries.put("BMU", "Bermuda");
        countries.put("BTN", "Bhutan");
        countries.put("BOL", "Bolivia (Plurinational State of)");
        countries.put("BES", "Bonaire, Sint Eustatius and Saba");
        countries.put("BIH", "Bosnia and Herzegovina");
        countries.put("BWA", "Botswana");
        countries.put("BVT", "Bouvet Island");
        countries.put("BRA", "Brazil");
        countries.put("IOT", "British Indian Ocean Territory");
        countries.put("VGB", "British Virgin Islands");
        countries.put("BRN", "Brunei Darussalam");
        countries.put("BGR", "Bulgaria");
        countries.put("BFA", "Burkina Faso");
        countries.put("BDI", "Burundi");
        countries.put("CPV", "Cabo Verde");
        countries.put("KHM", "Cambodia");
        countries.put("CMR", "Cameroon");
        countries.put("CAN", "Canada");
        countries.put("CYM", "Cayman Islands");
        countries.put("CAF", "Central African Republic");
        countries.put("TCD", "Chad");
        countries.put("CHL", "Chile");
        countries.put("CHN", "China");
        countries.put("HKG", "China, Hong Kong Special Administrative Region");
        countries.put("MAC", "China, Macao Special Administrative Region");
        countries.put("CXR", "Christmas Island");
        countries.put("CCK", "Cocos (Keeling) Islands");
        countries.put("COL", "Colombia");
        countries.put("COM", "Comoros");
        countries.put("COG", "Congo");
        countries.put("COK", "Cook Islands");
        countries.put("CRI", "Costa Rica");
        countries.put("CIV", "Côte d'Ivoire");
        countries.put("HRV", "Croatia");
        countries.put("CUB", "Cuba");
        countries.put("CUW", "Curaçao");
        countries.put("CYP", "Cyprus");
        countries.put("CZE", "Czechia");
        countries.put("PRK", "Democratic People's Republic of Korea");
        countries.put("COD", "Democratic Republic of the Congo");
        countries.put("DNK", "Denmark");
        countries.put("DJI", "Djibouti");
        countries.put("DMA", "Dominica");
        countries.put("DOM", "Dominican Republic");
        countries.put("ECU", "Ecuador");
        countries.put("EGY", "Egypt");
        countries.put("SLV", "El Salvador");
        countries.put("GNQ", "Equatorial Guinea");
        countries.put("ERI", "Eritrea");
        countries.put("EST", "Estonia");
        countries.put("ETH", "Ethiopia");
        countries.put("FLK", "Falkland Islands (Malvinas)");
        countries.put("FRO", "Faroe Islands");
        countries.put("FJI", "Fiji");
        countries.put("FIN", "Finland");
        countries.put("FRA", "France");
        countries.put("GUF", "French Guiana");
        countries.put("PYF", "French Polynesia");
        countries.put("ATF", "French Southern Territories");
        countries.put("GAB", "Gabon");
        countries.put("GMB", "Gambia");
        countries.put("GEO", "Georgia");
        countries.put("DEU", "Germany");
        countries.put("GHA", "Ghana");
        countries.put("GIB", "Gibraltar");
        countries.put("GRC", "Greece");
        countries.put("GRL", "Greenland");
        countries.put("GRD", "Grenada");
        countries.put("GLP", "Guadeloupe");
        countries.put("GUM", "Guam");
        countries.put("GTM", "Guatemala");
        countries.put("GGY", "Guernsey");
        countries.put("GIN", "Guinea");
        countries.put("GNB", "Guinea-Bissau");
        countries.put("GUY", "Guyana");
        countries.put("HTI", "Haiti");
        countries.put("HMD", "Heard Island and McDonald Islands");
        countries.put("VAT", "Holy See");
        countries.put("HND", "Honduras");
        countries.put("HUN", "Hungary");
        countries.put("ISL", "Iceland");
        countries.put("IND", "India");
        countries.put("IDN", "Indonesia");
        countries.put("IRN", "Iran (Islamic Republic of)");
        countries.put("IRQ", "Iraq");
        countries.put("IRL", "Ireland");
        countries.put("IMN", "Isle of Man");
        countries.put("ISR", "Israel");
        countries.put("ITA", "Italy");
        countries.put("JAM", "Jamaica");
        countries.put("JPN", "Japan");
        countries.put("JEY", "Jersey");
        countries.put("JOR", "Jordan");
        countries.put("KAZ", "Kazakhstan");
        countries.put("KEN", "Kenya");
        countries.put("KIR", "Kiribati");
        countries.put("KWT", "Kuwait");
        countries.put("KGZ", "Kyrgyzstan");
        countries.put("LAO", "Lao People's Democratic Republic");
        countries.put("LVA", "Latvia");
        countries.put("LBN", "Lebanon");
        countries.put("LSO", "Lesotho");
        countries.put("LBR", "Liberia");
        countries.put("LBY", "Libya");
        countries.put("LIE", "Liechtenstein");
        countries.put("LTU", "Lithuania");
        countries.put("LUX", "Luxembourg");
        countries.put("MDG", "Madagascar");
        countries.put("MWI", "Malawi");
        countries.put("MYS", "Malaysia");
        countries.put("MDV", "Maldives");
        countries.put("MLI", "Mali");
        countries.put("MLT", "Malta");
        countries.put("MHL", "Marshall Islands");
        countries.put("MTQ", "Martinique");
        countries.put("MRT", "Mauritania");
        countries.put("MUS", "Mauritius");
        countries.put("MYT", "Mayotte");
        countries.put("MEX", "Mexico");
        countries.put("FSM", "Micronesia (Federated States of)");
        countries.put("MCO", "Monaco");
        countries.put("MNG", "Mongolia");
        countries.put("MNE", "Montenegro");
        countries.put("MSR", "Montserrat");
        countries.put("MAR", "Morocco");
        countries.put("MOZ", "Mozambique");
        countries.put("MMR", "Myanmar");
        countries.put("NAM", "Namibia");
        countries.put("NRU", "Nauru");
        countries.put("NPL", "Nepal");
        countries.put("NLD", "Netherlands");
        countries.put("NCL", "New Caledonia");
        countries.put("NZL", "New Zealand");
        countries.put("NIC", "Nicaragua");
        countries.put("NER", "Niger");
        countries.put("NGA", "Nigeria");
        countries.put("NIU", "Niue");
        countries.put("NFK", "Norfolk Island");
        countries.put("MNP", "Northern Mariana Islands");
        countries.put("NOR", "Norway");
        countries.put("OMN", "Oman");
        countries.put("PAK", "Pakistan");
        countries.put("PLW", "Palau");
        countries.put("PAN", "Panama");
        countries.put("PNG", "Papua New Guinea");
        countries.put("PRY", "Paraguay");
        countries.put("PER", "Peru");
        countries.put("PHL", "Philippines");
        countries.put("PCN", "Pitcairn");
        countries.put("POL", "Poland");
        countries.put("PRT", "Portugal");
        countries.put("PRI", "Puerto Rico");
        countries.put("QAT", "Qatar");
        countries.put("KOR", "Republic of Korea");
        countries.put("MDA", "Republic of Moldova");
        countries.put("REU", "Réunion");
        countries.put("ROU", "Romania");
        countries.put("RUS", "Russian Federation");
        countries.put("RWA", "Rwanda");
        countries.put("BLM", "Saint Barthélemy");
        countries.put("SHN", "Saint Helena");
        countries.put("KNA", "Saint Kitts and Nevis");
        countries.put("LCA", "Saint Lucia");
        countries.put("MAF", "Saint Martin (French Part)");
        countries.put("SPM", "Saint Pierre and Miquelon");
        countries.put("VCT", "Saint Vincent and the Grenadines");
        countries.put("WSM", "Samoa");
        countries.put("SMR", "San Marino");
        countries.put("STP", "Sao Tome and Principe");
        countries.put("680", " ");
        countries.put("SAU", "Saudi Arabia");
        countries.put("SEN", "Senegal");
        countries.put("SRB", "Serbia");
        countries.put("SYC", "Seychelles");
        countries.put("SLE", "Sierra Leone");
        countries.put("SGP", "Singapore");
        countries.put("SXM", "Sint Maarten (Dutch part)");
        countries.put("SVK", "Slovakia");
        countries.put("SVN", "Slovenia");
        countries.put("SLB", "Solomon Islands");
        countries.put("SOM", "Somalia");
        countries.put("ZAF", "South Africa");
        countries.put("SGS", "South Georgia and the South Sandwich Islands");
        countries.put("SSD", "South Sudan");
        countries.put("ESP", "Spain");
        countries.put("LKA", "Sri Lanka");
        countries.put("PSE", "State of Palestine");
        countries.put("SDN", "Sudan");
        countries.put("SUR", "Suriname");
        countries.put("SJM", "Svalbard and Jan Mayen Islands");
        countries.put("SWZ", "Swaziland");
        countries.put("SWE", "Sweden");
        countries.put("CHE", "Switzerland");
        countries.put("SYR", "Syrian Arab Republic");
        countries.put("TJK", "Tajikistan");
        countries.put("THA", "Thailand");
        countries.put("MKD", "The former Yugoslav Republic of Macedonia");
        countries.put("TLS", "Timor-Leste");
        countries.put("TGO", "Togo");
        countries.put("TKL", "Tokelau");
        countries.put("TON", "Tonga");
        countries.put("TTO", "Trinidad and Tobago");
        countries.put("TUN", "Tunisia");
        countries.put("TUR", "Turkey");
        countries.put("TKM", "Turkmenistan");
        countries.put("TCA", "Turks and Caicos Islands");
        countries.put("TUV", "Tuvalu");
        countries.put("UGA", "Uganda");
        countries.put("UKR", "Ukraine");
        countries.put("ARE", "United Arab Emirates");
        countries.put("GBR", "United Kingdom of Great Britain and Northern Ireland");
        countries.put("TZA", "United Republic of Tanzania");
        countries.put("UMI", "United States Minor Outlying Islands");
        countries.put("USA", "United States of America");
        countries.put("VIR", "United States Virgin Islands");
        countries.put("URY", "Uruguay");
        countries.put("UZB", "Uzbekistan");
        countries.put("VUT", "Vanuatu");
        countries.put("VEN", "Venezuela (Bolivarian Republic of)");
        countries.put("VNM", "Viet Nam");
        countries.put("WLF", "Wallis and Futuna Islands");
        countries.put("ESH", "Western Sahara");
        countries.put("YEM", "Yemen");
        countries.put("ZMB", "Zambia");
        countries.put("ZWE", "Zimbabwe");
    }

    public String getCountry(String code) {
        if (code.length() > 3 && countries.containsValue(code)) {
            for (Map.Entry entry : countries.entrySet()) {
                if (((String) entry.getValue()).equalsIgnoreCase(code))
                    return (String) entry.getKey();
            }
        }
        return countries.getOrDefault(code, "Helpful error");
    }
}
